content:
  source:
    alias: prometheus-operator
    dockerfile: Dockerfile.config-reloader
from:
  builder:
  - image: openshift/golang-builder:1.10
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This component reloads a Prometheus server in a controlled and
    configurable way.
  io.k8s.display-name: Prometheus config reloader
  io.openshift.tags: prometheus
  vendor: Red Hat
name: openshift/ose-prometheus-config-reloader
owners:
- fbranczy@redhat.com
