#!/bin/bash

# To rebase against nightlies, define MICROSHIFT_PAYLOAD_X86_64 and MICROSHIFT_PAYLOAD_AARCH64
#   as the pullspecs of x86_64 and aarch64 release payloads.
# To rebase against a named release, define RELEASE_NAME.
# To not rebase at all, define MICROSHIFT_NO_REBASE=1

set -e

RELEASE_REPO="${RELEASE_REPO:-quay.io/openshift-release-dev/ocp-release}"

fail() {
    msg=$1
    >&2 echo "$msg"
    exit 1
}

# If MICROSHIFT_NO_REBASE is set and non-zero, stop execution here
if [ -n "$MICROSHIFT_NO_REBASE" ] && [ "$MICROSHIFT_NO_REBASE" -ne 0 ] ; then
    echo "MICROSHIFT_NO_REBASE is defined. Rebase will not be run."
    exit 0
fi


PODMAN_BUILD_CMD="podman build -t microshift-rebase ."
echo $DOCKER_BUILD_CMD
eval $DOCKER_BUILD_CMD

# Run the podman container
PODMAN_RUN_CMD="podman run --rm \
-e RELEASE_NAME \
-e LVMS_OPERATOR_BUNDLE \
-e MICROSHIFT_PAYLOAD_X86_64 \
-e MICROSHIFT_PAYLOAD_AARCH64 \
microshift-rebase"
echo $DOCKER_RUN_CMD
eval $DOCKER_RUN_CMD
