content:
  source:
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/machine-config-operator.git
    specfile: machine-config-daemon.spec
name: machine-config-daemon
owners:
  - coreos-devel@redhat.com
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-8
targets:
- rhaos-{MAJOR}.{MINOR}-rhel-8-candidate
