content:
  source:
    alias: node_exporter
    dockerfile: Dockerfile.rhel7
enabled_repos:
- rhel-server-ose-rpms
- rhel-server-ose-rpms-shipped
from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Prometheus exporter for hardware and OS metrics exposed by *NIX kernels, written in Go with pluggable metric collectors
  io.k8s.display-name: Node Exporter
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift3/prometheus-node-exporter
owners: []
