cachito:
  enabled: true
  packages:
    gomod:
    - path: rhobs-obo-prometheus-operator
content:
  source:
    pkg_managers:
    - gomod
    dockerfile: Containerfile.prom-operator
    git:
      branch:
        target: release-5.0
      url: git@github.com:openshift-priv/stolostron-obo-prometheus-operator.git
      web: https://github.com/stolostron/obo-prometheus-operator
distgit:
  component: acm-obo-prometheus-operator-container
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
delivery:
  delivery_repo_names:
  - rhacm2/obo-prometheus-rhel9-operator
dependents:
- multiclusterhub-operator
from:
  builder:
    - stream: rhel-9-golang
  member: base-rhel9
name: rhacm2/obo-prometheus-rhel9-operator
owners:
- acm-cicd@redhat.com
jira:
  project: ACM
  component: acm-obo-prometheus-operator-container
