content:
  source:
    dockerfile: Dockerfile.admission-webhook.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus-operator.git
      web: https://github.com/openshift/prometheus-operator
    ci_alignment:
      streams_prs:
        auto_label:
        - approved
        - backport-risk-assessed
        - cherry-pick-approved
        - lgtm
        - staff-eng-approved
        - jira/valid-reference
        - verified
        ci_build_root:
          member: ci-openshift-build-root-latest.rhel9
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: prometheus-operator-admission-webhook-container
delivery:
  # Maps to honeybadger repo_name
  repo_name: ose-prometheus-operator-admission-webhook
  delivery_repo_names:
  - openshift4/ose-prometheus-operator-admission-webhook-rhel9
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ose-prometheus-operator-admission-webhook-rhel9
payload_name: prometheus-operator-admission-webhook
owners:
- team-monitoring@redhat.com
