name: Run ocp-build-data-validator

on:
  pull_request:
    branches:
      - "openshift-**"
    paths:
      - "**.yml"
      - "rpms/**.yml"
      - "images/**.yml"

jobs:
  validate:
    uses: openshift-eng/ocp-build-data/.github/workflows/validate-reusable.yaml@main

